### PR TITLE
Implement opMemoize/opShortBinUnicode/opFrame from 'Protocol 4'

### PR DESCRIPTION
**Pull request by Sean-Der**
Hi @kisielk 

This is a work in progress, but I am working on adding some opcodes I need for fail2rest.

For [framing](https://www.python.org/dev/peps/pep-3154/#framing) is it worth implementing it? Performance/Complexity trade off.

The other thing I am worried I will mess up is loadShortBinUnicode, anytime I do stuff with variable-length encodings I always seem to mess it up..... so would appreciate close eyes on that one

I will update this PR when I have tests/all the opcodes from 'Protocol 4' in that I need.

### CODE REVIEW

**Comment by Sean-Der** [comment]
I just pushed some basic tests! Beyond the open question about framing I am not going to be pushing anything else to my fork (I need to keep it on master because I don't vender deps and just pull from master for fail2rest)

thanks

**Comment by kisielk** [comment]
Thanks for the patch Sean. I didn't know about these new protocol 4 features, haven't been following Python much lately :)

I guess in the current PR framing is still only partially implemented? from what I can see in the PEP it should first read 8 bytes to determine the size, and then decode M further opcodes.

**Comment by Sean-Der** [comment]
Just enjoying Golang :) I had no idea about protocol 4 either, but happy there was a nice PEP to describe all the new features (better than reading commits+code)

So, I *think* framing just exists so that a decoder doesn't have to do many little reads (Those 8 bytes could allow you to do a massive read and save time) Right now when we encounter a FRAME we just discard all this information.

While this feature could be nice, seemed like a bigger project (and not really useful for me) I don't need the performance, and didn't want to add the complexity.

**Comment by kisielk** [comment]
Oh I see, so your implementation just effectively ignores the framing opcodes and processes the framed portion as it would normally?

**Comment by Sean-Der** [comment]
ACK! Sorry I should have just said that in my PR/commit message.

I like writing code, the people part is not my skill ;)

**Comment by kisielk** [comment]
No problem :) Can you just add a comment to that method that it just discards the framing information? That way we don't get confused when looking at it in the future :) Then I think it's good to merge.

**Comment by Sean-Der** [comment]
@kisielk done! thanks for addressing this so quickly (and being so thorough with your feedback)

**Comment by kisielk** [comment]
Cool, thanks :)

**Pull request merged**
