### PR TITLE
fix when the first char is \, it cause UnquoteChar to return syntax e…

### PR DESCRIPTION
**Pull request by CodeRushing**
fix when the first char is \, it cause UnquoteChar to return syntax error

### CODE REVIEW

**Comment by kisielk** [comment]
Can you add a test for this please?

**Comment by CodeRushing** [comment]
I have already add a test case

**Comment by kisielk** [comment]
@dgryski does this look OK to you?

**Comment by CodeRushing** [comment]
I'm sorry that the first char of the string is not \. It's "`".

**Comment by CodeRushing** [comment]
I'm sorry that the first char of the string is not \。It's "'".

**Comment by dgryski** [comment]
LGTM

**Pull request merged**
