### PR TITLE
Make decode(encode(v)) to be identity + tuple

### PR DESCRIPTION
**Pull request by navytux**
Hello up there. Please find patches for the following attached:

1. Adjust encoder so that decode(encode(v)) == v.
2. Teach ogórek about tuple, so that go programs could produce pickle with real python tuples when needed.
3. Misc bug fixes.

Please see details in individual commit messages.
Patches here build on top of #32.

Thanks beforehand,
Kirill

### CODE REVIEW

**Comment by drawks** [comment]
This sounds awesome!

**Comment by navytux** [comment]
Patches rebased on top of current master. @kisielk please consider to "merge" the work, as all individual commits are prepared to do one thing at a time and do it well with proper description.

Thanks beforehand,
Kirill

**Comment by kisielk** [comment]
Thanks again :) Sorry, I didn't mean to squash the last one but was using github from the phone in the car, not sure why that became the default behaviour..

**Comment by navytux** [comment]
Thanks for merging and I see about applying the last time - no problem - it is a bit fun to think the patches there were applied while on the go. @drawks thanks also for your feedback.

**Pull request merged**
