### PR TITLE
ogórek v1.1.0

### PR DESCRIPTION
**Pull request by navytux**
- Add explicit support for modules and testing coverage for go1.12, go1.13, go1.14 and go1.15
- Document v1.0.0..v1.1.0 changes.

--------

Hello up there @kisielk. Could you please apply the patches and tag the result with v1.1.0 ? Currently, because the latest tag is v1.0.0 people, that use ogórek via modules, get outdated version with at least many known decoding bugs. If you are too busy I can do the release by myself if you give me write access to the repository. Hope it is ok.

Thanks beforehand,
Kirill

### CODE REVIEW

**Comment by kisielk** [comment]
Thanks for the patch! Will tag as v1.1.0

**Comment by navytux** [comment]
@kisielk, thanks for merging and for granting me write access.

**Comment by kisielk** [comment]
No problem. I am not regularly using this project at this point so if you are interested in helping maintain it that would be very much appreciated.

**Comment by navytux** [comment]
Thanks for feedback. I see. Yes, I'm actively using it in [ZODB/go](https://pkg.go.dev/lab.nexedi.com/kirr/neo/go/zodb) port and in particular in wendelin.core 2 to interchange in ZODB data arrays in between Python clients and Go [filesystem](https://lab.nexedi.com/kirr/wendelin.core/blob/5382e7b9/wcfs/wcfs.go) to represent those array data as synthethic files for mmap.

Given that ogórek is in actual use on my side I should be thus indeed in position to maintain it. Thanks for it.

**Pull request merged**
