### PR TITLE
decoder: Fix integer overflow in BYTEARRAY8 handling

### PR DESCRIPTION
**Pull request by navytux**
Please see individual patches for details.

P.S. Kamil, please do not squash the patches if you think this is ok and want to merge. I split the changes into two separate patches on purpose for easier understanding and better tracking. Thanks beforehand, Kirill.

### CODE REVIEW

**Comment by kisielk** [comment]
Thanks!

**Comment by navytux** [comment]
Thanks for merging, Kamil, that was fast!

P.S. I was meaning to apply the patches without merge commit, but also without squashing them into single patch. If I recall correctly this mode is also available on github.

**Comment by kisielk** [comment]
Ah yes, rebase and merge.. I'll try to remember to do that in the future. In any case not a big deal I think :)

**Comment by navytux** [comment]
Thanks, Kamil.

**Pull request merged**
